github: [huynhducduy]
patreon: huynhducduy
open_collective: huynhducduy
ko_fi: huynhducduy
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: huynhducduy
liberapay: huynhducduy
issuehunt: huynhducduy
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: huynhducduy
buy_me_a_coffee: huynhducduy
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
